# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e395c394978df8b84a5a381f661df7f3be10accf8f1b310233693af8aaf78f8f023569971f9c8869f405e70a9a5802d492cd44b6ea77c118e1fe30d43c6a488f

test:
  secret_key_base: 4486c6a8cbe96010651cd0728feec2f6a6361802762865fddb4b583e3dac4f4a09a1d47fa78a3c65d46d3407fd1d4a2678ee6ca234d90e59fa61b4e05ca7ef89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
